project:
  type: book
  output-dir: docs

book:
  title: "Learning Diary"
  author: "Owen Hughes"
  date: "1/20/2026"
  chapters:
    - index.qmd
    - Week1.qmd
    - intro.qmd
    - summary.qmd

bibliography: Chap_References.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

